<?xml version="1.0" ?>
<!DOCTYPE dialogue [
<!ELEMENT dialogue (metadata, entry*)>
<!ELEMENT metadata (gender, age_group, nationality, first_language, english_skills, education, tech_savviness, date_of_interaction, amount_of_turns, distinct_clarification_type_count)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT age_group (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT first_language (#PCDATA)>
<!ELEMENT english_skills (#PCDATA)>
<!ELEMENT education (#PCDATA)>
<!ELEMENT tech_savviness (#PCDATA)>
<!ELEMENT date_of_interaction (#PCDATA)>
<!ELEMENT amount_of_turns (#PCDATA)>
<!ELEMENT distinct_clarification_type_count (#PCDATA)>
<!ELEMENT entry (start_ms, speaker, text, scenario, clarification_turn?, clarification_type?, clarification_span?)>
<!ELEMENT start_ms (#PCDATA)>
<!ELEMENT speaker (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT scenario (#PCDATA)>
<!ELEMENT clarification_turn (#PCDATA)>
<!ELEMENT clarification_type (#PCDATA)>
<!ELEMENT clarification_span (#PCDATA)>
]>
<dialogue>
    <metadata>
        <gender>Female</gender>
        <age_group>26-35</age_group>
        <nationality>German</nationality>
        <first_language>German</first_language>
        <english_skills>Advanced</english_skills>
        <education>Secondary education</education>
        <tech_savviness>Intermediate</tech_savviness>
        <date_of_interaction>27/05/2024</date_of_interaction>
        <amount_of_turns>71</amount_of_turns>
        <distinct_clarification_type_count>5</distinct_clarification_type_count>
    </metadata>
    <entry>
        <start_ms>1440</start_ms>
        <speaker>Participant</speaker>
        <text>temi temi come to me please</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>5110</start_ms>
        <speaker>TEMI</speaker>
        <text>hello {participant} how can i assist you</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>8070</start_ms>
        <speaker>Participant</speaker>
        <text>hello temi can you come to me please</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>13534</start_ms>
        <speaker>TEMI</speaker>
        <text>sure ((temi comes to participant)) (5.0)</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>20694</start_ms>
        <speaker>Participant</speaker>
        <text>can you maybe turn around</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>22206</start_ms>
        <speaker>TEMI</speaker>
        <text>how is this</text>
        <scenario>1</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 11]</clarification_span>
    </entry>
    <entry>
        <start_ms>24214</start_ms>
        <speaker>Participant</speaker>
        <text>this is perfect can you maybe turn around so i can scan the back of you</text>
        <scenario>1</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 71]</clarification_span>
    </entry>
    <entry>
        <start_ms>31874</start_ms>
        <speaker>TEMI</speaker>
        <text>why do you want me to turn around</text>
        <scenario>1</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Evaluating intention</clarification_type>
        <clarification_span>[0, 33]</clarification_span>
    </entry>
    <entry>
        <start_ms>34674</start_ms>
        <speaker>Participant</speaker>
        <text>i would like to scan the qr code on your back</text>
        <scenario>1</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Evaluating intention</clarification_type>
        <clarification_span>[0, 45]</clarification_span>
    </entry>
    <entry>
        <start_ms>40720</start_ms>
        <speaker>TEMI</speaker>
        <text>okay in which direction do you want to engage in a rotational realignment</text>
        <scenario>1</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 73]</clarification_span>
    </entry>
    <entry>
        <start_ms>45920</start_ms>
        <speaker>Participant</speaker>
        <text>you can turn around one hundred eighty degrees</text>
        <scenario>1</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 46]</clarification_span>
    </entry>
    <entry>
        <start_ms>55694</start_ms>
        <speaker>TEMI</speaker>
        <text>in which direction</text>
        <scenario>1</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 18]</clarification_span>
    </entry>
    <entry>
        <start_ms>57174</start_ms>
        <speaker>Participant</speaker>
        <text>to the right  ((temi turns around)) (14.0)</text>
        <scenario>1</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 12]</clarification_span>
    </entry>
    <entry>
        <start_ms>80394</start_ms>
        <speaker>TEMI</speaker>
        <text>how is this</text>
        <scenario>1</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 11]</clarification_span>
    </entry>
    <entry>
        <start_ms>81706</start_ms>
        <speaker>Participant</speaker>
        <text>this is perfect thank you temi is happy</text>
        <scenario>1</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 15]</clarification_span>
    </entry>
    <entry>
        <start_ms>94474</start_ms>
        <speaker>TEMI</speaker>
        <text>can i turn back now</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>97194</start_ms>
        <speaker>Participant</speaker>
        <text>one second please</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>101834</start_ms>
        <speaker>TEMI</speaker>
        <text>sorry</text>
        <scenario>1</scenario>
    </entry>
    <entry>
        <start_ms>103564</start_ms>
        <speaker>Participant</speaker>
        <text>temi can you maybe go to the kitchen and check if the light is turned on or turned off</text>
        <scenario>2</scenario>
    </entry>
    <entry>
        <start_ms>122084</start_ms>
        <speaker>TEMI</speaker>
        <text>you want me to check if the fridge is open</text>
        <scenario>2</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 42]</clarification_span>
    </entry>
    <entry>
        <start_ms>124764</start_ms>
        <speaker>Participant</speaker>
        <text>oh sorry temi no can you check if the light is turned on or is it turned off</text>
        <scenario>2</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 76]</clarification_span>
    </entry>
    <entry>
        <start_ms>133373</start_ms>
        <speaker>TEMI</speaker>
        <text>sorry i didn't understand could you repeat that please</text>
        <scenario>2</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Acoustic issue</clarification_type>
        <clarification_span>[6, 54]</clarification_span>
    </entry>
    <entry>
        <start_ms>137733</start_ms>
        <speaker>Participant</speaker>
        <text>can you go to the kitchen and check if the light is turned on</text>
        <scenario>2</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Acoustic issue</clarification_type>
        <clarification_span>[0, 61]</clarification_span>
    </entry>
    <entry>
        <start_ms>145213</start_ms>
        <speaker>TEMI</speaker>
        <text>apologies you want me to check if the kitchen light is switched off</text>
        <scenario>2</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 67]</clarification_span>
    </entry>
    <entry>
        <start_ms>149573</start_ms>
        <speaker>Participant</speaker>
        <text>yes perfect</text>
        <scenario>2</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 3]</clarification_span>
    </entry>
    <entry>
        <start_ms>155085</start_ms>
        <speaker>TEMI</speaker>
        <text>sure i will check ((temi goes to the kitchen)) (46.0)</text>
        <scenario>2</scenario>
    </entry>
    <entry>
        <start_ms>156714</start_ms>
        <speaker>Participant</speaker>
        <text>thank you</text>
        <scenario>2</scenario>
    </entry>
    <entry>
        <start_ms>204734</start_ms>
        <speaker>TEMI</speaker>
        <text>i just checked in the kitchen the light is off was that the information that you were looking for</text>
        <scenario>2</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 97]</clarification_span>
    </entry>
    <entry>
        <start_ms>211024</start_ms>
        <speaker>Participant</speaker>
        <text>yes thank you temi</text>
        <scenario>2</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 3]</clarification_span>
    </entry>
    <entry>
        <start_ms>214224</start_ms>
        <speaker>TEMI</speaker>
        <text>you're welcome</text>
        <scenario>2</scenario>
    </entry>
    <entry>
        <start_ms>218144</start_ms>
        <speaker>Participant</speaker>
        <text>oh can you now go to the kitchen and get me the book your handbook</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>230304</start_ms>
        <speaker>TEMI</speaker>
        <text>do you want me to get the book or just check if there is a book in the kitchen</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 78]</clarification_span>
    </entry>
    <entry>
        <start_ms>233912</start_ms>
        <speaker>Participant</speaker>
        <text>no you can come get it for me please</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 29]</clarification_span>
    </entry>
    <entry>
        <start_ms>242284</start_ms>
        <speaker>TEMI</speaker>
        <text>so you want me to get the book for you</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 38]</clarification_span>
    </entry>
    <entry>
        <start_ms>244380</start_ms>
        <speaker>Participant</speaker>
        <text>yes please</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 3]</clarification_span>
    </entry>
    <entry>
        <start_ms>249920</start_ms>
        <speaker>TEMI</speaker>
        <text>sure i am on my way ((temi goes to the kitchen)) (46.0)</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 19]</clarification_span>
    </entry>
    <entry>
        <start_ms>251884</start_ms>
        <speaker>Participant</speaker>
        <text>thank you so much</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>301074</start_ms>
        <speaker>TEMI</speaker>
        <text>there are two books in the kitchen one about statistics and one about robots which one do you want</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 98]</clarification_span>
    </entry>
    <entry>
        <start_ms>308194</start_ms>
        <speaker>Participant</speaker>
        <text>i would like the book about robots</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 34]</clarification_span>
    </entry>
    <entry>
        <start_ms>315544</start_ms>
        <speaker>TEMI</speaker>
        <text>sorry i didn't understand could you repeat that please</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Acoustic issue</clarification_type>
        <clarification_span>[6, 47]</clarification_span>
    </entry>
    <entry>
        <start_ms>319424</start_ms>
        <speaker>Participant</speaker>
        <text>can you get me the book about robots from the kitchen please</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Acoustic issue</clarification_type>
        <clarification_span>[0, 53]</clarification_span>
    </entry>
    <entry>
        <start_ms>324544</start_ms>
        <speaker>TEMI</speaker>
        <text>you want me to bring you the book about robots is that correct</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 62]</clarification_span>
    </entry>
    <entry>
        <start_ms>327952</start_ms>
        <speaker>Participant</speaker>
        <text>yes</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 3]</clarification_span>
    </entry>
    <entry>
        <start_ms>331620</start_ms>
        <speaker>TEMI</speaker>
        <text>sure i will get you the book ((temi goes to the kitchen)) (60.0)</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 28]</clarification_span>
    </entry>
    <entry>
        <start_ms>333320</start_ms>
        <speaker>Participant</speaker>
        <text>thank you</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>396764</start_ms>
        <speaker>TEMI</speaker>
        <text>i got you the book is this the book you wanted</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 46]</clarification_span>
    </entry>
    <entry>
        <start_ms>402324</start_ms>
        <speaker>Participant</speaker>
        <text>can you turn around please [one hundred eighty degrees to the  (intelligible)]</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>407092</start_ms>
        <speaker>TEMI</speaker>
        <text>[sure] ((temi turns around)) (5.0)</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>414664</start_ms>
        <speaker>TEMI</speaker>
        <text>how is this</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 11]</clarification_span>
    </entry>
    <entry>
        <start_ms>416384</start_ms>
        <speaker>Participant</speaker>
        <text>this is the statistics book but that's fine as well thank you very much</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 71]</clarification_span>
    </entry>
    <entry>
        <start_ms>425184</start_ms>
        <speaker>TEMI</speaker>
        <text>oh you want me to get the other book</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>428864</start_ms>
        <speaker>Participant</speaker>
        <text>i think one is fine </text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>435201</start_ms>
        <speaker>Participant</speaker>
        <text>no come get me the uh book about robots robots as well please</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>440684</start_ms>
        <speaker>TEMI</speaker>
        <text>okay on my way ((temi goes to the kitchen)) (46.0)</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>444684</start_ms>
        <speaker>Participant</speaker>
        <text>thank you</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>483624</start_ms>
        <speaker>TEMI</speaker>
        <text>i got you the second book is this the book you wanted</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation after action</clarification_type>
        <clarification_span>[0, 53]</clarification_span>
    </entry>
    <entry>
        <start_ms>490104</start_ms>
        <speaker>Participant</speaker>
        <text>can uh you turn around again please</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>495264</start_ms>
        <speaker>TEMI</speaker>
        <text>in what direction</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 17]</clarification_span>
    </entry>
    <entry>
        <start_ms>496792</start_ms>
        <speaker>Participant</speaker>
        <text>one hundred eighty degrees to the right please</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Request more information</clarification_type>
        <clarification_span>[0, 39]</clarification_span>
    </entry>
    <entry>
        <start_ms>502504</start_ms>
        <speaker>TEMI</speaker>
        <text>to the right</text>
        <scenario>3</scenario>
        <clarification_turn>i</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 12]</clarification_span>
    </entry>
    <entry>
        <start_ms>503552</start_ms>
        <speaker>Participant</speaker>
        <text>yes ((temi turns around)) (5.0)</text>
        <scenario>3</scenario>
        <clarification_turn>f</clarification_turn>
        <clarification_type>Confirmation before action </clarification_type>
        <clarification_span>[0, 3]</clarification_span>
    </entry>
    <entry>
        <start_ms>509118</start_ms>
        <speaker>Participant</speaker>
        <text>perfect thank you so much</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>517824</start_ms>
        <speaker>TEMI</speaker>
        <text>you're welcome</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>522094</start_ms>
        <speaker>Participant</speaker>
        <text>you were a big help today</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>525534</start_ms>
        <speaker>TEMI</speaker>
        <text>is there anything else i can do</text>
        <scenario>3</scenario>
    </entry>
    <entry>
        <start_ms>527814</start_ms>
        <speaker>Participant</speaker>
        <text>no i don't think so thank you very much</text>
        <scenario>3</scenario>
    </entry>
</dialogue>
